### ISSUE TITLE
[feat]: caching

### ISSUE THREAD

**Issue by jkuri** [bleenco/abstruse#132]
Caching directories in builds that are not changed ofter. This will speed up builds significantly.
Good example of cached directory is `node_modules/`.

**Comment by captn3m0** [comment]
@jkuri Is it possible to have configurable caching? Not all languages are covered in the defaults, and I'd much rather prefer a dumb `/cache` mount, which is usable by just setting the cache directory path correctly. (This is how Wercker does it)

For eg: `composer config cache-dir $ABSTRUSE_CACHE_DIR` works better than hardcoding the path, since the `vendor` directory might not necessarily be in the repo root.

I like the Travis approach as well: Have some hardcoded paths for default caching support out of the box, but allow cache-mounts.

**Comment by jkuri** [comment]
sure, you can set cached directories like so:
```
cache:
  - node_modules/
  - dist/
```
in your `.abstruse.yml` configuration, [here](https://github.com/bleenco/abstruse/blob/master/.abstruse.yml#L21-L22) is an example.
