### ISSUE TITLE
[bug] GitHub api url is not used everywhere

### ISSUE THREAD

**Issue by matthax** [bleenco/abstruse#350]
The GitHub url set on the main configuration page is not used everywhere throughout the application, which can cause a few bugs. For example the build fails because the [commit status service](https://github.com/bleenco/abstruse/blob/1e4c846c270ed8864750c4dd174705ca76dddb31/src/api/commit-status.ts#L13) does not use the right endpoint. 

This results in an error like the following: ```request to https://api.github.com/repos/:org/:repo/statuses/:sha failed with error code 401```

The other place I noticed the issue was in the [api service](https://github.com/bleenco/abstruse/blob/c0f442939206e7b31703e459aaf66b4f8404c0b2/src/app/services/api.service.ts#L181) file, but I have not noticed any issues caused by that, yet.

**Comment by jkuri** [comment]
Hi Matt!

You are right about hardcoded github url, in fact the whole `commit-status.ts` should be refactored and this has high priority on my todo list. thanks for pointing that out, I will try to refactor this as as soon as possible and use url from the repository settings.

The other place you discovered hardcoded github url is used for frontend fetching of avatar images of users. I need to do that because in some of github api responses committer or authors data is not complete but has only username or something provided. This was also done in a hurry and would break on GitHub Enterprise solutions hosted on different URLs.

**Comment by jkuri** [comment]
For development you need to run two scripts, first is for API:
```sh
$ npm run dev
```
and the second is for the frontend:
```sh
$ npm start
```
then use `http://localhost:4200` url in the browser.

**Comment by matthax** [comment]
Was able to trigger the build and set statuses successfully:
![image](https://user-images.githubusercontent.com/12008400/38334626-cd078848-3829-11e8-81d7-fcaa371fd83f.png)
