### ISSUE TITLE
[feat] use GitHub apps

### ISSUE THREAD

**Issue by matthax** [bleenco/abstruse#351]
It would be great if we could use Abstruse as a GitHub application instead of providing user access tokens. Abstruse would simply need to accept a private key used to sign it's own JWT for api requests. Here is an example of what the configuration would look like for github enterprise users.

![image](https://user-images.githubusercontent.com/12008400/38330225-ff6272a0-381d-11e8-8674-ea51a01f9bb9.png)

**Comment by jkuri** [comment]
This is a good idea and would definitely improve the setup of the abstruse. Also screenshot looks pretty simple and straightforward. I believe implementation of that would not be difficult but we need to investigate of how this should be done, some points you already stated, thanks. 

I will mark this with priority medium since there are many other bugs that should be resolved first but this will be implemented in the future for sure.

**Comment by matthax** [comment]
If I have some time I would be happy to make some of the enhancements.

In order to integrate with the API the user needs to configure the app, I can provide instructions on how to do this for enterprise.

Next the app needs to be installed, at this point Abstruse would receive a payload from github with an ID, this ID is used to sign JWT tokens.

Next, the user needs to download the private key for the app and move it onto the CI server. The path to the key needs to be set (probably the config.json file) so Abstruse knows it can use the Github app.

Then, the option to use the app integration must be available when choosing the access token. When this option is chosen, Abstruse can sign the token used to make requests, instead of using the personal access token.


A JWT library would be required, I use `jsonwebtoken` but I'm open to other suggestions.

I'm not sure if the API calls using the access token are sent using the `Authorization: Bearer` header - if not, that would need to change as well.

**Comment by jkuri** [comment]
Very good, thanks. Every PR is welcome here since I am very busy lately and have no or little time except for the weekends to continue development on Abstruse. I will sure find time to continue dev here in the future, hopefully soon.

Your specification seems cool, I would only change saving private keys path from `config.json` to database for example, otherwise the whole abstruse service needs to be restarted. It would be also nice that uploading private key would be possible via web UI, we can collaborate on that, if you'll need help maybe. 

We already use `jsonwebtoken` package, it is included [here](https://github.com/bleenco/abstruse/blob/master/package.json#L96) so no worries about that.

btw, can you please squash commits on your current pr so I can merge the fix?

**Comment by jkuri** [comment]
Forgot one thing; instructions about integration, you can put that in a new `.md` file inside `docs/`.

**Comment by matthax** [comment]
Should the token be uploaded as a file and then the path stored in the database? I've not worked much with SqlLite so I'm not sure how well it handles larger data. I'll do some research, but any input/suggestions are appreciated

**Comment by matthax** [comment]
I think the best approach would be a checkbox/switch on the setting page that signified whether or not it was a key. If it is a key we can create a .key file and put the path into the database, that would allow us to keep the database size down but also prevent restarts when keys are added or removed.

**Comment by jkuri** [comment]
SQLite can easily handle larger sets of data. This was also mine first project using this database and I must say that it works very well.
Token should be stored as string imho, I had in mind certificate before.

**Comment by matthax** [comment]
Okay the key store as a string is less effort, that's the approach I will take

**Comment by matthax** [comment]
Sample permissions:
![image](https://user-images.githubusercontent.com/12008400/38372499-f9edd52c-38bc-11e8-918c-0988e9807b40.png)

Sample events:

![image](https://user-images.githubusercontent.com/12008400/38372571-2903a486-38bd-11e8-8fa7-5df63f1e30a3.png)

**Comment by matthax** [comment]
Working on this now, I'm not sure how to go about integrating tests since they would have to be run in an enterprise environment.

It would be possible to do a few checks based on whether or not a value was set, but an e2e test based only on the app integration, will likely not be possible.

**Comment by matthax** [comment]
![image](https://user-images.githubusercontent.com/12008400/38450144-f7a8d2a0-39e6-11e8-8e0e-3684f3e6d243.png)

Adding the GitHub app key
