### ISSUE TITLE
[question] Deploy stage starts as new build

### ISSUE THREAD

**Issue by dedkat** [bleenco/abstruse#384]
It's possible to not start new build for deployment stage?
Now, deploy stage wait's for positive end of of the "script" phase but when it starts it start as new build .

**Comment by jkuri** [comment]
Currently that is not possible but I see what you mean, you would like to copy build artifacts from some other container to the "deployment" container. Maybe that could be a feature for the `2.0.0` release as  I see it as a good time improvement for deployment process, but I am not sure how would configuration look like in that case in `.abstruse.yml`. I am open to suggestions.

**Comment by dedkat** [comment]
Hm, not really. What I want is not have to install some small apps in deployment stage. But it has no sense for me to clone repository again ... but I can be wrong ;)
Of course I can install everything in build image and my problem dissapear. Also I can deploy my app in "script" or "after_successful" stage. Too many options sometimes can generate unnecessary problems :)

**Comment by jkuri** [comment]
If you have a single test job then `after_successful` would work, but I believe you don't want to deploy multiple times from each job that you are running in build so this is not a good solution at all. 
Currently I do not see any better way than to add additional option in configuration for using different image for deployment, but that would still clone repository again.

**Comment by dedkat** [comment]
I build my app as docker image, so my deployment is basically only "docker push" and script that reload services - so for me, downloading repo is  unnecessary - but  it's only me, and I understand that for other purposes it could be useful. But I'm used to stagings in drone.io, where every step works on the same once downloaded repository.

**Comment by jkuri** [comment]
okay, got you now. you would need something like Jenkins build pipelines or Drones stage builds. 
there is already opened issue for that [here](https://github.com/bleenco/abstruse/issues/378) but I unfortunatelly did not have time yet to implement it. That will definitely land in `2.0.0` release which will also include distributed builds where you can run abstruse workers on multiple servers.

I am currently really short with time due to work for customers but as soon as my schedule release this will be done.

Just a quick question for curiosity; what did you or your team liked on `abstruse` so you decided to switch from `drone`? I would like to know where our product is better or differs from others so we can put more focus on that direction and improve features in that way. thanks!

**Comment by dedkat** [comment]
We didn't move yet, but I wan't to try use it because drone isn't to elastic, you can do there easily lot of things but it's limited by plugins. Sometimes plugins didn't give you some options, and then you have to make your own version of it. 
Idea of using docker images in drone as plugins is great ... but it force you to configure multiple of them in one pipeline, sometimes you have to use them twice or even more ... and your pipeline start to look creepy.
In abstruse it's easy to automate your repo to build/test/deploy it in the same way on your workstation and on CI/CD server ... but it has stil some lacks ;)

**Comment by jkuri** [comment]
thank you for the feedback. yes, it does. can you specify what bothers you most in current version and I will make a list of fixes or features for next release. critics from users are the best, and it would help as a lot to improve abstruse so one day it would be a cool product.

**Comment by dedkat** [comment]
Thanks, I will create a list in the near future :)

**Comment by irmana** [comment]
@dedkat did you capture ideas from this thread in https://github.com/bleenco/abstruse/issues/388 ? I would close it if you don't mind, please give thumbs up.
