### ISSUE TITLE
[feat] Add an option to react on builds and comment

### ISSUE THREAD

**Issue by irmana** [bleenco/abstruse#396]
Currently, page for jobs and logs is boring (see below). 

![image](https://user-images.githubusercontent.com/3041169/44089215-3e46d03c-9fc6-11e8-9937-e1366db7a0c8.png)
![image](https://user-images.githubusercontent.com/3041169/44089231-4ee1e09e-9fc6-11e8-8ece-fc77a94ce67d.png)

We propose to add an option to react on build/jobs and leave an overall comment or comment line within console output. This would reduce the communication channels needed and keep the relevant discussion stored in a system, i.e. Slack messages often get lost as it's hard to find the relevant content afterwards. It would also make abstruse more social CI.

- [ ] React (thumbs up, smile, etc.) and comment on build to make it more social. 
- [ ] Comment on lines in console output, e.g. like github line comments. Then this lines should be included in jobs page like in a github discussion, e.g. https://github.com/bleenco/abstruse/pull/360

**Comment by ad-m** [comment]
Is it really important to make a communication channel build-in in CI? It is a tool that supports others in most of the integration, eg where the source code is stored. Many places where you leave a comment distracts communication. 

Is there other social-oriented CI? How do users use communication in it?

In my opinion, you should at least provide a way to add to build link where you can discuss the topic, where the notification was sent. It mean link to pull request, link to slack message (I am not sure there is way to link messages in Slack). Putting comments inside CI will only cause communication chaos in teams.

**Comment by ForsakenHarmony** [comment]
I feel like being able to link lines in the output would be enough to then comment on the pull request

**Comment by cooperaj** [comment]
I think @ad-m is onto something there. In full stack platforms such as Gitlab, Visual Studio Online or Bitbucket being able to comment on just about everything is helped by the fact that *all* the things you need to do with code is in one place. 

But someone using abstruse is just using it as CI so the value in being able to comment there is a bit less, since they'll be absolutely using something else to communicate. Being able to link to exact lines however is pretty useful. Especially if you can use that incoming link to build appropriate OpenGraph data. Something like Slack would then pick that up and show a decent preview too.
