### ISSUE TITLE
Is there a way to manually trigger build for specific commit other than webhook?

### ISSUE THREAD

**Issue by ganapativs** [bleenco/abstruse#410]
Note: This is not a issue, but a discussion.

We want to integrate abstruse with our custom deployment flow. We can't integrate with GitHub webhook because we don't deploy and run test cases on each commit(yet).

We use [cypress](cypress.io) test suite, so our use case is, we deploy on staging/pre-prod and when the staging/pre-prod site is up and running, we want to run our cypress test cases.

Is there any way to achieve this using abstruse or can someone suggest a flow that works well with abstruse?

**Comment by paullaffitte** [comment]
I would need this feature too, or at least something to ignore some branches (currently it start an empty and instantaneous build if the branch is ignored).

The reason why I need this feature is that I need to setup a constant delivery on our master branch. So we do our features, merge them in develop, push it, merge it with master, push master, and then we would like to deploy our code on the master push but only on this one.

Since we neither have tests yet, others branches are just useless in our deployment process and it can be enjoyable to not have 90% of our builds finishing in 0.0s but rather than that only the builds we are interested in.

A workaround could be to be able to filter build by duration allowing us to hide empty build and focus on builds doing something.

**Comment by arthurchaloin** [comment]
I am interested into this too. I'd like to be able to submit a custom payload to an API route that will trigger a manual build. I see this is already done for testing purposes (using the `/trigger-test-build/:repositoryId` API call). This would only imply extracting the route code into a more generic function that will be called either by the `/trigger-test-build/:repositoryId` route or by a new one (e.g. `/trigger-manual-build/:repositoryId`). I can code and PR if you guys tells me that you're alright with this.

**Comment by orensbruli** [comment]
+1

**Comment by jkuri** [comment]
there is a section `config` under repository settings where you test your config and manually trigger a build.
![Screenshot 2020-12-09 at 16 53 59](https://user-images.githubusercontent.com/1796022/101653163-56e30000-3a3f-11eb-9a97-d5f0586be132.png)
