### ISSUE TITLE
Allow adding single repositories

### ISSUE THREAD

**Issue by Aeolun** [bleenco/abstruse#417]
I've been trying very hard to find any form of CI that does this, but every single CI application (except for Travis, which sucks) wants me to give them an OAuth master key so they can access the entire set of repositories in one go.

Unfortunately, I do not have, and cannot have, the master key for our organisations's Bitbucket Server account, but I still want to use a nice CI system. What I want, is to just stick in a deployment SSH key, and manually give the system a list of git repositories to check (ideally not polling, but to allow me to give the system a webhook post/get to notify it when something changed).

Is this something that would be possible in abstruse?

Edit: Actually, after further investigation, I do feel like abstruse is already most of the way there. I really only need a webhook that accepts Bitbucket Server webhooks and an image that has an ssh key baked in. Would you be open to a pull request that adds that?

**Comment by jkuri** [comment]
Bitbucket server is the one that is self-hosted? If the answer is yes, then I need to dissapoint you since abstruse is not supporting that. I am not sure why but all webhooks are in different format than on hosted bitbucket.org. I once investigated on that and we would also need to develop plugin for Bitbucket so we can make this working with abstruse. Sorry to say that, but this is not even planned to be scheduled on this project.
